version: '3'

services:

  nginx:
    image: alicates/nginx
    ports: 
      - "80:80"
    volumes:
      - /var/lib/jenkins/jobs/:/usr/share/nginx/
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
