version: '3'

services:

  nginx:
    image: cabama/nginx
    build: nginx/.
    ports: 
      - "80:80"
    networks: 
      - hormiguitas
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager


volumes:
  portainer_data:



networks:
  hormiguitas:
