version: '3'

services:

  jenkins:
    image: carlos/jenkins:lts
    build: jenkins/.
    user: jenkins
    networks:
      - hormiguitas
    volumes:
      - /root/install/jenkins/data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_HOST_HOME: "/data/jenkins"
    ports:
      - "8282:8080"
      - "5000:5000"
      - "50000:50000"
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  nginx:
    image: carlos/nginx
    build: nginx/.
    ports: 
      - "80:80"
    networks: 
      - hormiguitas
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - hormiguitas
volumes:
  portainer_data:

networks:
  hormiguitas:
